name: Run pdk test unit and validate

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: "Setup ruby"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: "Bundle environment"
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: "Run Static & Syntax Tests"
      run: |
        bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
        bundle exec dependency-checker metadata.json

    - name: "Run tests"
      run: |
        bundle exec rake parallel_spec

